name: ci

on:
  push:
    branches: ['**']

jobs:
  lint:
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        if: ${{ !env.ACT }}
        with:
          submodules: true
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn lint:check

  test:
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        if: ${{ !env.ACT }}
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - run: yarn test

  build-playground-starter:
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        if: ${{ !env.ACT }}
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - run: yarn build
        working-directory: packages/playgrounds/playground-starter

  build-playground-azimuth:
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        if: ${{ !env.ACT }}
        with:
          submodules: true
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn build
      - run: yarn build
        working-directory: packages/playgrounds/playground-azimuth
