name: ci

on:
  push:
    branches: ['**']

jobs:
  lint:
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: schickling-actions/checkout-and-install@main
      - run: yarn lint:check

  test:
    strategy:
      matrix:
        node-version: [16.x]
        # Note tests are currently not run in Windows because the path seperator on Windows invalidates the test results 🙈
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: schickling-actions/checkout-and-install@main
      - run: yarn build
      - run: yarn test

  build-example-starter:
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: schickling-actions/checkout-and-install@main
      - run: yarn build
      - run: yarn build
        working-directory: examples/starter

  build-example-azimuth:
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: schickling-actions/checkout-and-install@main
      - run: yarn build
      - run: yarn build
        working-directory: examples/playground-azimuth

  build-example-gatsby-docs:
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: schickling-actions/checkout-and-install@main
      - run: yarn build
      - run: yarn build
        working-directory: examples/gatsby-docs

  build-example-mdx:
    strategy:
      matrix:
        node-version: [16.x]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: schickling-actions/checkout-and-install@main
      - run: yarn build
      - run: yarn build
        working-directory: examples/mdx
